
compile:
	javac -cp .:java-cup-v11a.jar semant/Main.java

run:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/test.while

divtest:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/divtest.while

factorial:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/factorial.while

factorize:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/factorize.while

fibonacci:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/fibonacci.while

gcd:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/gcd.while

infinite:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/infinite.while

nestedtry:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/nestedtry.while

time:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/time.while

trycatchsample:
	javac -cp .:java-cup-v11a.jar semant/Main.java

	java -cp .:java-cup-v11a.jar semant.Main samples/trycatchsample.while